#!/usr/bin/env python3
"""
core/sheets_writer.py
KPI Platform — writes enriched data back to Google Sheets.

Updates tabs each pipeline run:
  CURRENT          → Clear + rewrite with current week (12 rows)
  STYLISTS_CURRENT → Clear + rewrite with current week stylists
  ALERTS           → Clear + rewrite with AI-generated alerts (rows 100-101 = coach briefs)
  DATA             → Append current week rows (idempotent — skips if week already present)
  STYLISTS_DATA    → Append current week stylist rows (idempotent — skips if week already present)
"""

import os
import json
import base64
import logging
import datetime
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build

log = logging.getLogger(__name__)

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]


def _build_service(config: dict):
    raw_b64 = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
    if not raw_b64:
        raise EnvironmentError("GOOGLE_SERVICE_ACCOUNT_JSON env var is not set.")
    sa_json = base64.b64decode(raw_b64).decode("utf-8")
    sa_info = json.loads(sa_json)
    creds = service_account.Credentials.from_service_account_info(sa_info, scopes=SCOPES)
    return build("sheets", "v4", credentials=creds)


def _clear_and_write(service, sheet_id: str, tab_range: str, rows: list[list]):
    """Clear a range then write new rows."""
    service.spreadsheets().values().clear(
        spreadsheetId=sheet_id,
        range=tab_range,
    ).execute()

    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range=tab_range,
        valueInputOption="USER_ENTERED",
        body={"values": rows},
    ).execute()


# ─── CURRENT tab ──────────────────────────────────────────────────────────────

def write_current(service, config: dict, locations: list[dict], dry_run: bool = False):
    """Rewrite the CURRENT tab with this week's location snapshot."""
    if dry_run:
        log.info("DRY RUN: skipping CURRENT tab write (%d rows)", len(locations))
        return

    sheet_id = config["sheet_id"]
    rows = []
    for loc in locations:
        rows.append([
            loc.get("loc_name", ""),
            loc.get("week_ending", ""),
            loc.get("platform", ""),
            loc.get("guests", 0),
            loc.get("total_sales", 0),
            loc.get("service", 0),
            loc.get("product", 0),
            loc.get("product_pct", 0),
            loc.get("ppg", 0),
            loc.get("pph", 0),
            loc.get("avg_ticket", 0),
            loc.get("prod_hours", 0),
            loc.get("wax_count", 0),
            loc.get("wax", 0),
            loc.get("wax_pct", 0),
            loc.get("color", 0),
            loc.get("color_pct", 0),
            loc.get("treat_count", 0),
            loc.get("treat", 0),
            loc.get("treat_pct", 0),
        ])

    _clear_and_write(service, sheet_id, "CURRENT!A2:T", rows)
    log.info("CURRENT tab: wrote %d location rows", len(rows))


# ─── STYLISTS_CURRENT tab ─────────────────────────────────────────────────────

def write_stylists_current(service, config: dict, stylists: list[dict], dry_run: bool = False):
    """Rewrite STYLISTS_CURRENT with this week's stylist snapshot."""
    if dry_run:
        log.info("DRY RUN: skipping STYLISTS_CURRENT tab write (%d rows)", len(stylists))
        return

    sheet_id = config["sheet_id"]
    rows = []
    for s in stylists:
        # Get current week (last entry)
        week = s["weeks"][-1] if s.get("weeks") else ""
        rows.append([
            week,
            s.get("name", ""),
            s.get("loc_name", ""),
            s.get("loc_id", ""),
            s.get("status", "active"),
            s.get("tenure", 0),
            s.get("cur_pph", 0),
            s.get("cur_rebook", 0),
            s.get("cur_product", 0),
            s.get("cur_ticket", 0),
            s["services"][-1] if s.get("services") else 0,
            s["color"][-1] if s.get("color") else 0,
        ])

    _clear_and_write(service, sheet_id, "STYLISTS_CURRENT!A2:L", rows)
    log.info("STYLISTS_CURRENT tab: wrote %d stylist rows", len(rows))


# ─── ALERTS tab ───────────────────────────────────────────────────────────────

def _build_alerts(locations: list[dict], network: dict, ai_cards: dict) -> list[list]:
    """
    Generate alert rows from enriched location data and AI cards.
    Returns list of [Location Name, Alert Type, Severity, Message, Week Ending, Generated By]
    """
    rows = []
    week = network.get("week_ending", "")

    for loc in locations:
        name = loc["loc_name"]
        flag = loc.get("flag", "solid")
        card = ai_cards.get("location_cards", {}).get(name, "")

        if flag == "star":
            rows.append([name, "RECOGNITION", "LOW", card or f"Strong performance this week.", week, "KPI AI"])
        elif flag == "watch":
            rows.append([name, "WATCH", "HIGH", card or f"Performance below network average — coach attention recommended.", week, "KPI AI"])

        # Product % alert
        prod_delta = loc.get("product_pct_delta")
        if prod_delta is not None and prod_delta <= -3.0:
            rows.append([
                name, "PRODUCT_DROP", "MEDIUM",
                f"Product % dropped {abs(prod_delta):.1f} points vs last week ({loc['product_pct']:.1f}%).",
                week, "KPI AI"
            ])

        # PPH alert
        pph_delta_pct = loc.get("pph_delta_pct")
        if pph_delta_pct is not None and pph_delta_pct <= -5.0:
            rows.append([
                name, "PPH_DROP", "MEDIUM",
                f"PPH dropped {abs(pph_delta_pct):.1f}% vs last week (${loc['pph']:.2f}).",
                week, "KPI AI"
            ])

    # Add coach briefing as a network-level alert
    briefing = ai_cards.get("coach_briefing", "")
    if briefing:
        # Just add first 250 chars as a summary alert
        summary = briefing[:250].replace("\n", " ").strip()
        rows.append(["ALL LOCATIONS", "COACH BRIEFING", "LOW", summary, week, "KPI AI"])

    return rows


def write_alerts(
    service,
    config: dict,
    locations: list[dict],
    network: dict,
    ai_cards: dict,
    dry_run: bool = False,
):
    """Rewrite the ALERTS tab with this week's AI-generated alerts."""
    alert_rows = _build_alerts(locations, network, ai_cards)

    if dry_run:
        log.info("DRY RUN: ALERTS tab would get %d rows:", len(alert_rows))
        for row in alert_rows:
            log.info("  [%s] %s — %s", row[2], row[0], row[3][:60])
        return

    sheet_id = config["sheet_id"]
    _clear_and_write(service, sheet_id, "ALERTS!A2:F", alert_rows)
    log.info("ALERTS tab: wrote %d alert rows", len(alert_rows))


# ─── COACH BRIEFS (ALERTS tab rows 100–101) ───────────────────────────────────

def write_coach_briefs(
    service,
    config: dict,
    coach_cards: dict,
    week_ending: str,
    dry_run: bool = False,
):
    """
    Write JESS_BRIEF and JENN_BRIEF as key-value rows into the ALERTS tab
    at fixed positions A100:F101 — well beyond where regular alert rows reach.

    Dashboard reads these rows by scanning for the key in column A.

    Preservation rule: if a card dict is missing or empty for a manager,
    that row is NOT overwritten — the previous week's value stays in place.
    This is safe because we use update() (not clear+write) for these rows.
    """
    if not coach_cards:
        log.info("No coach cards provided — skipping ALERTS brief rows")
        return

    # Fixed row layout: JESS at row 100, JENN at row 101
    row_map = [
        ("Jess", "JESS_BRIEF", 100),
        ("Jenn", "JENN_BRIEF", 101),
    ]

    if dry_run:
        for manager_name, row_key, _ in row_map:
            card = coach_cards.get(manager_name)
            if card:
                log.info("DRY RUN: Would write %s to ALERTS row (key=%s, %d chars JSON)",
                         manager_name, row_key, len(json.dumps(card)))
            else:
                log.info("DRY RUN: No card for %s — would preserve existing row", manager_name)
        return

    sheet_id = config["sheet_id"]

    for manager_name, row_key, row_num in row_map:
        card = coach_cards.get(manager_name)
        if not card:
            log.warning(
                "Coach card for %s is missing — preserving ALERTS!A%d (previous week kept)",
                manager_name, row_num
            )
            continue

        row_data = [
            row_key,
            "COACH_BRIEF",
            "INFO",
            json.dumps(card, separators=(",", ":")),
            week_ending,
            "KPI AI",
        ]

        service.spreadsheets().values().update(
            spreadsheetId=sheet_id,
            range=f"ALERTS!A{row_num}:F{row_num}",
            valueInputOption="USER_ENTERED",
            body={"values": [row_data]},
        ).execute()

        log.info("ALERTS!A%d: wrote %s brief (%d chars JSON)", row_num, row_key, len(row_data[3]))

    log.info("Coach briefs write complete (dry_run=%s)", dry_run)


# ─── DATA tab (historical append) ─────────────────────────────────────────────

def append_to_historical(service, config: dict, locations: list[dict], dry_run: bool = False):
    """Append this week's location rows to the DATA tab (idempotent).

    Reads DATA!B2:B to check whether this week_ending is already present.
    If so, skips the write — safe to re-run on the same week.
    """
    if not locations:
        log.info("append_to_historical: no locations — skipping")
        return

    week_ending = locations[0].get("week_ending", "")

    if dry_run:
        log.info(
            "DRY RUN: append_to_historical — would append %d rows for week_ending=%s",
            len(locations), week_ending,
        )
        return

    sheet_id = config["sheet_id"]

    # Idempotency check — skip if this week is already in DATA!B2:B
    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="DATA!B2:B",
    ).execute()
    existing_weeks = {r[0] for r in existing.get("values", []) if r}
    if week_ending and week_ending in existing_weeks:
        log.info(
            "append_to_historical: week_ending=%s already in DATA tab — skipping",
            week_ending,
        )
        return

    rows = []
    for loc in locations:
        rows.append([
            loc.get("loc_name", ""),
            loc.get("week_ending", ""),
            loc.get("platform", ""),
            loc.get("guests", 0),
            loc.get("total_sales", 0),
            loc.get("service", 0),
            loc.get("product", 0),
            loc.get("product_pct", 0),
            loc.get("ppg", 0),
            loc.get("pph", 0),
            loc.get("avg_ticket", 0),
            loc.get("prod_hours", 0),
            loc.get("wax_count", 0),
            loc.get("wax", 0),
            loc.get("wax_pct", 0),
            loc.get("color", 0),
            loc.get("color_pct", 0),
            loc.get("treat_count", 0),
            loc.get("treat", 0),
            loc.get("treat_pct", 0),
        ])

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="DATA!A2:T",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()

    log.info("DATA tab: appended %d location rows for week_ending=%s", len(rows), week_ending)


# ─── STYLISTS_DATA tab (historical append) ────────────────────────────────────

def append_to_stylists_historical(
    service,
    config: dict,
    stylists: list[dict],
    week_ending: str,
    dry_run: bool = False,
):
    """Append this week's stylist rows to the STYLISTS_DATA tab (idempotent).

    Reads STYLISTS_DATA!A2:A to check whether this week_ending is already present.
    If so, skips the write — safe to re-run on the same week.
    """
    if not stylists:
        log.info("append_to_stylists_historical: no stylists — skipping")
        return

    if dry_run:
        log.info(
            "DRY RUN: append_to_stylists_historical — would append %d rows for week_ending=%s",
            len(stylists), week_ending,
        )
        return

    sheet_id = config["sheet_id"]

    # Idempotency check — skip if this week is already in STYLISTS_DATA!A2:A
    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA!A2:A",
    ).execute()
    existing_weeks = {r[0] for r in existing.get("values", []) if r}
    if week_ending and week_ending in existing_weeks:
        log.info(
            "append_to_stylists_historical: week_ending=%s already in STYLISTS_DATA tab — skipping",
            week_ending,
        )
        return

    rows = []
    for s in stylists:
        rows.append([
            week_ending,
            s.get("name", ""),
            s.get("loc_name", ""),
            s.get("loc_id", ""),
            s.get("status", "active"),
            s.get("tenure_yrs", 0),
            s.get("cur_pph", 0),
            s.get("cur_rebook", 0),
            s.get("cur_product", 0),
            s.get("cur_ticket", 0),
            s["services"][-1] if s.get("services") else 0,
            s["color"][-1] if s.get("color") else 0,
        ])

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA!A2:L",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()

    log.info(
        "STYLISTS_DATA tab: appended %d stylist rows for week_ending=%s",
        len(rows), week_ending,
    )


# ─── Dual-write shadow hook (v2 parallel Sheet) ───────────────────────────────
#
# This is the bridge between the legacy pipeline and the new v2 Sheets. It is
# OFF by default. Flip it on by setting:
#
#     DUAL_WRITE_V2=true        # enable the shadow write
#     V2_MASTER_SHEET_ID=<id>   # v2 master sheet ID
#     V2_COACH_SHEET_ID=<id>    # optional — v2 coach cards sheet ID
#     V2_DRY_RUN=true|false     # override (defaults to the outer dry_run)
#
# The legacy write runs first and is the source of truth. The v2 write runs
# AFTER and is wrapped so any failure (auth, schema mismatch, network) is
# logged but never propagates — production must continue exactly as before.

def _dual_write_v2_enabled() -> bool:
    return os.environ.get("DUAL_WRITE_V2", "").strip().lower() in ("1", "true", "yes", "on")


def _dual_write_v2(
    data: dict,
    coach_cards: dict | None,
    dry_run: bool,
) -> None:
    """
    Shadow-write the enriched pipeline output to the v2 Sheet.
    Never raises — all failures are logged at WARNING.
    """
    if not _dual_write_v2_enabled():
        return

    try:
        master_id = os.environ.get("V2_MASTER_SHEET_ID", "").strip()
        if not master_id:
            log.warning("DUAL_WRITE_V2: V2_MASTER_SHEET_ID not set — skipping shadow write")
            return

        # v2 dry-run defaults to the outer dry_run, but can be overridden.
        v2_dry_env = os.environ.get("V2_DRY_RUN", "").strip().lower()
        if v2_dry_env in ("1", "true", "yes", "on"):
            v2_dry = True
        elif v2_dry_env in ("0", "false", "no", "off"):
            v2_dry = False
        else:
            v2_dry = dry_run

        # Import lazily so this module stays importable without v2 deps on the
        # path (the v2 code imports gspread + our schema module; neither is
        # required for the legacy pipeline).
        from core.google_sheets_store import GoogleSheetsStore
        from core.schema_mapper import (
            map_coach_briefs,
            map_location_rows,
            map_stylist_rows,
        )

        store = GoogleSheetsStore(
            master_sheet_id=master_id,
            coach_cards_sheet_id=os.environ.get("V2_COACH_SHEET_ID") or None,
            dry_run=v2_dry,
        )

        locations = data.get("locations") or []
        stylists = data.get("stylists") or []
        week_ending = data.get("network", {}).get("week_ending", "")

        v2_locations = map_location_rows(locations)
        v2_stylists = map_stylist_rows(stylists, period_end=week_ending)

        caller = "core.sheets_writer.write_all"

        store.write_locations_current(v2_locations, caller=caller)
        store.append_locations_historical(v2_locations, caller=caller)
        store.write_stylists_current(v2_stylists, caller=caller)
        store.append_stylists_historical(v2_stylists, caller=caller)

        if coach_cards:
            briefs = map_coach_briefs(coach_cards)
            if briefs:
                store.write_coach_briefs(
                    briefs,
                    period_end=week_ending,
                    model="",  # model name threaded through in a later phase
                    caller=caller,
                )

        log.info("DUAL_WRITE_V2: shadow write complete (dry_run=%s)", v2_dry)
    except Exception as e:  # noqa: BLE001 — must never propagate
        log.warning(
            "DUAL_WRITE_V2: shadow write failed (non-fatal — legacy write succeeded): %s",
            e,
        )


# ─── Main entry ───────────────────────────────────────────────────────────────

def write_all(
    config: dict,
    data: dict,
    ai_cards: dict,
    coach_cards: dict | None = None,
    dry_run: bool = False,
):
    """Write CURRENT, STYLISTS_CURRENT, ALERTS, coach brief rows, and historical appends in one call."""
    service = _build_service(config) if not dry_run else None
    write_current(service, config, data["locations"], dry_run)
    write_stylists_current(service, config, data["stylists"], dry_run)
    write_alerts(service, config, data["locations"], data["network"], ai_cards, dry_run)

    week_ending = data["network"].get("week_ending", "")

    if coach_cards:
        write_coach_briefs(service, config, coach_cards, week_ending, dry_run)

    append_to_historical(service, config, data["locations"], dry_run)
    append_to_stylists_historical(service, config, data["stylists"], week_ending, dry_run)

    # v2 shadow write — OFF by default, gated by DUAL_WRITE_V2 env var.
    # Runs AFTER legacy writes succeed; any v2 failure is logged, not raised.
    _dual_write_v2(data, coach_cards, dry_run)

    log.info("Sheets write complete (dry_run=%s)", dry_run)
