#!/usr/bin/env python3
"""
core/sheets_writer.py
KPI Platform — writes enriched data back to Google Sheets.

Updates tabs each pipeline run:
  CURRENT          → Clear + rewrite with current week (12 rows)
  STYLISTS_CURRENT → Clear + rewrite with current week stylists
  ALERTS           → Clear + rewrite with AI-generated alerts (rows 100-101 = coach briefs)
  DATA             → Append current week rows (idempotent — skips if week already present)
  STYLISTS_DATA    → Append current week stylist rows (idempotent — skips if week already present)
"""

import os
import json
import base64
import logging
import datetime
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build

log = logging.getLogger(__name__)

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]


def _build_service(config: dict):
    raw_b64 = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
    if not raw_b64:
        raise EnvironmentError("GOOGLE_SERVICE_ACCOUNT_JSON env var is not set.")
    sa_json = base64.b64decode(raw_b64).decode("utf-8")
    sa_info = json.loads(sa_json)
    creds = service_account.Credentials.from_service_account_info(sa_info, scopes=SCOPES)
    return build("sheets", "v4", credentials=creds)


def _clear_and_write(service, sheet_id: str, tab_range: str, rows: list[list]):
    """Clear a range then write new rows."""
    service.spreadsheets().values().clear(
        spreadsheetId=sheet_id,
        range=tab_range,
    ).execute()

    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range=tab_range,
        valueInputOption="USER_ENTERED",
        body={"values": rows},
    ).execute()


# ─── CURRENT tab ──────────────────────────────────────────────────────────────

def write_current(service, config: dict, locations: list[dict], dry_run: bool = False):
    """Rewrite the CURRENT tab with this week's location snapshot."""
    if dry_run:
        log.info("DRY RUN: skipping CURRENT tab write (%d rows)", len(locations))
        return

    sheet_id = config["sheet_id"]
    rows = []
    for loc in locations:
        rows.append([
            loc.get("loc_name", ""),
            loc.get("week_ending", ""),
            loc.get("platform", ""),
            loc.get("guests", 0),
            loc.get("total_sales", 0),
            loc.get("service", 0),
            loc.get("product", 0),
            loc.get("product_pct", 0),
            loc.get("ppg", 0),
            loc.get("pph", 0),
            loc.get("avg_ticket", 0),
            loc.get("prod_hours", 0),
            loc.get("wax_count", 0),
            loc.get("wax", 0),
            loc.get("wax_pct", 0),
            loc.get("color", 0),
            loc.get("color_pct", 0),
            loc.get("treat_count", 0),
            loc.get("treat", 0),
            loc.get("treat_pct", 0),
        ])

    _clear_and_write(service, sheet_id, "CURRENT!A2:T", rows)
    log.info("CURRENT tab: wrote %d location rows", len(rows))


# ─── STYLISTS_CURRENT tab ─────────────────────────────────────────────────────

def write_stylists_current(service, config: dict, stylists: list[dict], dry_run: bool = False):
    """Rewrite STYLISTS_CURRENT with this week's stylist snapshot."""
    if dry_run:
        log.info("DRY RUN: skipping STYLISTS_CURRENT tab write (%d rows)", len(stylists))
        return

    sheet_id = config["sheet_id"]
    rows = []
    for s in stylists:
        # Get current week (last entry)
        week = s["weeks"][-1] if s.get("weeks") else ""
        rows.append([
            week,
            s.get("name", ""),
            s.get("loc_name", ""),
            s.get("loc_id", ""),
            s.get("status", "active"),
            s.get("tenure", 0),
            s.get("cur_pph", 0),
            s.get("cur_rebook", 0),
            s.get("cur_product", 0),
            s.get("cur_ticket", 0),
            s["services"][-1] if s.get("services") else 0,
            s["color"][-1] if s.get("color") else 0,
        ])

    _clear_and_write(service, sheet_id, "STYLISTS_CURRENT!A2:L", rows)
    log.info("STYLISTS_CURRENT tab: wrote %d stylist rows", len(rows))


# ─── ALERTS tab ───────────────────────────────────────────────────────────────

def _build_alerts(locations: list[dict], network: dict, ai_cards: dict) -> list[list]:
    """
    Generate alert rows from enriched location data and AI cards.
    Returns list of [Location Name, Alert Type, Severity, Message, Week Ending, Generated By]
    """
    rows = []
    week = network.get("week_ending", "")

    for loc in locations:
        name = loc["loc_name"]
        flag = loc.get("flag", "solid")
        card = ai_cards.get("location_cards", {}).get(name, "")

        if flag == "star":
            rows.append([name, "RECOGNITION", "LOW", card or f"Strong performance this week.", week, "KPI AI"])
        elif flag == "watch":
            rows.append([name, "WATCH", "HIGH", card or f"Performance below network average — coach attention recommended.", week, "KPI AI"])

        # Product % alert
        prod_delta = loc.get("product_pct_delta")
        if prod_delta is not None and prod_delta <= -3.0:
            rows.append([
                name, "PRODUCT_DROP", "MEDIUM",
                f"Product % dropped {abs(prod_delta):.1f} points vs last week ({loc['product_pct']:.1f}%).",
                week, "KPI AI"
            ])

        # PPH alert
        pph_delta_pct = loc.get("pph_delta_pct")
        if pph_delta_pct is not None and pph_delta_pct <= -5.0:
            rows.append([
                name, "PPH_DROP", "MEDIUM",
                f"PPH dropped {abs(pph_delta_pct):.1f}% vs last week (${loc['pph']:.2f}).",
                week, "KPI AI"
            ])

    # Add coach briefing as a network-level alert
    briefing = ai_cards.get("coach_briefing", "")
    if briefing:
        # Just add first 250 chars as a summary alert
        summary = briefing[:250].replace("\n", " ").strip()
        rows.append(["ALL LOCATIONS", "COACH BRIEFING", "LOW", summary, week, "KPI AI"])

    return rows


def write_alerts(
    service,
    config: dict,
    locations: list[dict],
    network: dict,
    ai_cards: dict,
    dry_run: bool = False,
):
    """Rewrite the ALERTS tab with this week's AI-generated alerts."""
    alert_rows = _build_alerts(locations, network, ai_cards)

    if dry_run:
        log.info("DRY RUN: ALERTS tab would get %d rows:", len(alert_rows))
        for row in alert_rows:
            log.info("  [%s] %s — %s", row[2], row[0], row[3][:60])
        return

    sheet_id = config["sheet_id"]
    _clear_and_write(service, sheet_id, "ALERTS!A2:F", alert_rows)
    log.info("ALERTS tab: wrote %d alert rows", len(alert_rows))


# ─── COACH BRIEFS (ALERTS tab rows 100–101) ───────────────────────────────────

def write_coach_briefs(
    service,
    config: dict,
    coach_cards: dict,
    week_ending: str,
    dry_run: bool = False,
):
    """
    Write JESS_BRIEF and JENN_BRIEF as key-value rows into the ALERTS tab
    at fixed positions A100:F101 — well beyond where regular alert rows reach.

    Dashboard reads these rows by scanning for the key in column A.

    Preservation rule: if a card dict is missing or empty for a manager,
    that row is NOT overwritten — the previous week's value stays in place.
    This is safe because we use update() (not clear+write) for these rows.
    """
    if not coach_cards:
        log.info("No coach cards provided — skipping ALERTS brief rows")
        return

    # Fixed row layout: JESS at row 100, JENN at row 101
    row_map = [
        ("Jess", "JESS_BRIEF", 100),
        ("Jenn", "JENN_BRIEF", 101),
    ]

    if dry_run:
        for manager_name, row_key, _ in row_map:
            card = coach_cards.get(manager_name)
            if card:
                log.info("DRY RUN: Would write %s to ALERTS row (key=%s, %d chars JSON)",
                         manager_name, row_key, len(json.dumps(card)))
            else:
                log.info("DRY RUN: No card for %s — would preserve existing row", manager_name)
        return

    sheet_id = config["sheet_id"]

    for manager_name, row_key, row_num in row_map:
        card = coach_cards.get(manager_name)
        if not card:
            log.warning(
                "Coach card for %s is missing — preserving ALERTS!A%d (previous week kept)",
                manager_name, row_num
            )
            continue

        row_data = [
            row_key,
            "COACH_BRIEF",
            "INFO",
            json.dumps(card, separators=(",", ":")),
            week_ending,
            "KPI AI",
        ]

        service.spreadsheets().values().update(
            spreadsheetId=sheet_id,
            range=f"ALERTS!A{row_num}:F{row_num}",
            valueInputOption="USER_ENTERED",
            body={"values": [row_data]},
        ).execute()

        log.info("ALERTS!A%d: wrote %s brief (%d chars JSON)", row_num, row_key, len(row_data[3]))

    log.info("Coach briefs write complete (dry_run=%s)", dry_run)


# ─── DATA tab (historical append) ─────────────────────────────────────────────

def append_to_historical(service, config: dict, locations: list[dict], dry_run: bool = False):
    """Append this week's location rows to the DATA tab (idempotent).

    Reads DATA!B2:B to check whether this week_ending is already present.
    If so, skips the write — safe to re-run on the same week.
    """
    if not locations:
        log.info("append_to_historical: no locations — skipping")
        return

    week_ending = locations[0].get("week_ending", "")

    if dry_run:
        log.info(
            "DRY RUN: append_to_historical — would append %d rows for week_ending=%s",
            len(locations), week_ending,
        )
        return

    sheet_id = config["sheet_id"]

    # Idempotency check — skip if this week is already in DATA!B2:B
    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="DATA!B2:B",
    ).execute()
    existing_weeks = {r[0] for r in existing.get("values", []) if r}
    if week_ending and week_ending in existing_weeks:
        log.info(
            "append_to_historical: week_ending=%s already in DATA tab — skipping",
            week_ending,
        )
        return

    rows = []
    for loc in locations:
        rows.append([
            loc.get("loc_name", ""),
            loc.get("week_ending", ""),
            loc.get("platform", ""),
            loc.get("guests", 0),
            loc.get("total_sales", 0),
            loc.get("service", 0),
            loc.get("product", 0),
            loc.get("product_pct", 0),
            loc.get("ppg", 0),
            loc.get("pph", 0),
            loc.get("avg_ticket", 0),
            loc.get("prod_hours", 0),
            loc.get("wax_count", 0),
            loc.get("wax", 0),
            loc.get("wax_pct", 0),
            loc.get("color", 0),
            loc.get("color_pct", 0),
            loc.get("treat_count", 0),
            loc.get("treat", 0),
            loc.get("treat_pct", 0),
        ])

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="DATA!A2:T",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()

    log.info("DATA tab: appended %d location rows for week_ending=%s", len(rows), week_ending)


# ─── STYLISTS_DATA tab (historical append) ────────────────────────────────────

def append_to_stylists_historical(
    service,
    config: dict,
    stylists: list[dict],
    week_ending: str,
    dry_run: bool = False,
):
    """Append this week's stylist rows to the STYLISTS_DATA tab (idempotent).

    Reads STYLISTS_DATA!A2:A to check whether this week_ending is already present.
    If so, skips the write — safe to re-run on the same week.
    """
    if not stylists:
        log.info("append_to_stylists_historical: no stylists — skipping")
        return

    if dry_run:
        log.info(
            "DRY RUN: append_to_stylists_historical — would append %d rows for week_ending=%s",
            len(stylists), week_ending,
        )
        return

    sheet_id = config["sheet_id"]

    # Idempotency check — skip if this week is already in STYLISTS_DATA!A2:A
    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA!A2:A",
    ).execute()
    existing_weeks = {r[0] for r in existing.get("values", []) if r}
    if week_ending and week_ending in existing_weeks:
        log.info(
            "append_to_stylists_historical: week_ending=%s already in STYLISTS_DATA tab — skipping",
            week_ending,
        )
        return

    rows = []
    for s in stylists:
        rows.append([
            week_ending,
            s.get("name", ""),
            s.get("loc_name", ""),
            s.get("loc_id", ""),
            s.get("status", "active"),
            s.get("tenure_yrs", 0),
            s.get("cur_pph", 0),
            s.get("cur_rebook", 0),
            s.get("cur_product", 0),
            s.get("cur_ticket", 0),
            s["services"][-1] if s.get("services") else 0,
            s["color"][-1] if s.get("color") else 0,
        ])

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA!A2:L",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()

    log.info(
        "STYLISTS_DATA tab: appended %d stylist rows for week_ending=%s",
        len(rows), week_ending,
    )


# ─── DATA_MONTHLY tab (historical backfill, monthly grain) ────────────────────
#
# DATA_MONTHLY parallels DATA at monthly grain. It exists so backfill / YOY /
# MTD pacing features have history without polluting weekly-grain consumers
# (projection_eom math, WoW deltas, the Monday pipeline append path).
#
# Idempotency key is (loc_name, year_month). Schema mirrors DATA except
# `week_ending` is replaced by `year_month`, and three provenance columns
# are appended:
#     U source        — "tracker" | "zenoti_monthly_pdf" | "su_monthly_pdf"
#     V period_start  — actual YYYY-MM-DD start date covered
#     W period_end    — actual YYYY-MM-DD end date covered (may be < last
#                       day of month for partial months like May 2026 5/1-5/24)

DATA_MONTHLY_HEADERS = [
    "loc_name", "year_month", "platform",
    "guests", "total_sales", "service", "product", "product_pct",
    "ppg", "pph", "avg_ticket", "prod_hours",
    "wax_count", "wax", "wax_pct",
    "color", "color_pct",
    "treat_count", "treat", "treat_pct",
    "source", "period_start", "period_end",
]


def _ensure_data_monthly_tab(service, sheet_id: str) -> None:
    """Create DATA_MONTHLY with a header row if the tab doesn't exist."""
    meta = service.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing_titles = {s["properties"]["title"] for s in meta.get("sheets", [])}
    if "DATA_MONTHLY" in existing_titles:
        return

    log.info("DATA_MONTHLY tab not found — creating with header row")
    service.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": "DATA_MONTHLY"}}}]},
    ).execute()
    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range="DATA_MONTHLY!A1:W1",
        valueInputOption="USER_ENTERED",
        body={"values": [DATA_MONTHLY_HEADERS]},
    ).execute()


def append_to_data_monthly(
    service,
    config: dict,
    rows: list[dict],
    dry_run: bool = False,
):
    """Append monthly aggregate rows to DATA_MONTHLY (idempotent on loc_name+year_month).

    Each row dict supplies the 23 fields named in ``DATA_MONTHLY_HEADERS``.
    Missing fields default to "" for strings and 0 for numerics.

    Reads DATA_MONTHLY!A2:B to find existing (loc_name, year_month) keys and
    skips rows whose key is already present — safe to re-run on the same
    month.
    """
    if not rows:
        log.info("append_to_data_monthly: no rows — skipping")
        return

    year_months = sorted({r.get("year_month", "") for r in rows if r.get("year_month")})

    if dry_run:
        log.info(
            "DRY RUN: append_to_data_monthly — would append %d rows for year_months=%s",
            len(rows), year_months,
        )
        return

    sheet_id = config["sheet_id"]

    _ensure_data_monthly_tab(service, sheet_id)

    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="DATA_MONTHLY!A2:B",
    ).execute()
    existing_keys = {
        (r[0], r[1]) for r in existing.get("values", []) if len(r) >= 2
    }

    new_rows = []
    for r in rows:
        key = (r.get("loc_name", ""), r.get("year_month", ""))
        if key in existing_keys:
            log.info(
                "append_to_data_monthly: skipping existing (loc=%s, year_month=%s)",
                key[0], key[1],
            )
            continue
        new_rows.append([
            r.get("loc_name", ""),
            r.get("year_month", ""),
            r.get("platform", ""),
            r.get("guests", 0),
            r.get("total_sales", 0),
            r.get("service", 0),
            r.get("product", 0),
            r.get("product_pct", 0),
            r.get("ppg", 0),
            r.get("pph", 0),
            r.get("avg_ticket", 0),
            r.get("prod_hours", 0),
            r.get("wax_count", 0),
            r.get("wax", 0),
            r.get("wax_pct", 0),
            r.get("color", 0),
            r.get("color_pct", 0),
            r.get("treat_count", 0),
            r.get("treat", 0),
            r.get("treat_pct", 0),
            r.get("source", ""),
            r.get("period_start", ""),
            r.get("period_end", ""),
        ])

    if not new_rows:
        log.info("append_to_data_monthly: all rows already present — nothing to write")
        return

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="DATA_MONTHLY!A2:W",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows},
    ).execute()

    log.info(
        "DATA_MONTHLY tab: appended %d location-month rows (year_months=%s)",
        len(new_rows), year_months,
    )


# ─── STYLISTS_DATA_MONTHLY tab (historical backfill, monthly stylist grain) ───
#
# Mirrors DATA_MONTHLY but at stylist grain. Idempotency key is
# (year_month, name, loc_name) — three columns. Same dry-run + auto-create
# semantics as append_to_data_monthly.
#
# Fields that aren't supplied by all sources (e.g. SU PDFs don't have
# per-stylist invoices count, Zenoti xlsxes don't have production_hours)
# default to 0 or "". The `source` column records provenance.

STYLISTS_DATA_MONTHLY_HEADERS = [
    "year_month", "name", "loc_name", "loc_id", "platform",
    "invoices", "guests", "net_service", "net_product",
    "avg_ticket", "pph", "ppg", "production_hours",
    "source", "period_start", "period_end",
]


def _ensure_stylists_data_monthly_tab(service, sheet_id: str) -> None:
    """Create STYLISTS_DATA_MONTHLY with a header row if the tab is missing."""
    meta = service.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing_titles = {s["properties"]["title"] for s in meta.get("sheets", [])}
    if "STYLISTS_DATA_MONTHLY" in existing_titles:
        return

    log.info("STYLISTS_DATA_MONTHLY tab not found — creating with header row")
    service.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": "STYLISTS_DATA_MONTHLY"}}}]},
    ).execute()
    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA_MONTHLY!A1:P1",
        valueInputOption="USER_ENTERED",
        body={"values": [STYLISTS_DATA_MONTHLY_HEADERS]},
    ).execute()


def append_to_stylists_data_monthly(
    service,
    config: dict,
    rows: list[dict],
    dry_run: bool = False,
):
    """Append stylist-monthly rows. Idempotent on (year_month, name, loc_name)."""
    if not rows:
        log.info("append_to_stylists_data_monthly: no rows — skipping")
        return

    year_months = sorted({r.get("year_month", "") for r in rows if r.get("year_month")})

    if dry_run:
        log.info(
            "DRY RUN: append_to_stylists_data_monthly — would append %d rows for year_months=%s",
            len(rows), year_months,
        )
        return

    sheet_id = config["sheet_id"]

    _ensure_stylists_data_monthly_tab(service, sheet_id)

    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA_MONTHLY!A2:C",
    ).execute()
    existing_keys = {
        (r[0], r[1], r[2]) for r in existing.get("values", []) if len(r) >= 3
    }

    new_rows = []
    for r in rows:
        key = (r.get("year_month", ""), r.get("name", ""), r.get("loc_name", ""))
        if key in existing_keys:
            log.info(
                "append_to_stylists_data_monthly: skipping existing (ym=%s, name=%s, loc=%s)",
                *key,
            )
            continue
        new_rows.append([
            r.get("year_month", ""),
            r.get("name", ""),
            r.get("loc_name", ""),
            r.get("loc_id", ""),
            r.get("platform", ""),
            r.get("invoices", 0),
            r.get("guests", 0),
            r.get("net_service", 0),
            r.get("net_product", 0),
            r.get("avg_ticket", 0),
            r.get("pph", 0),
            r.get("ppg", 0),
            r.get("production_hours", 0),
            r.get("source", ""),
            r.get("period_start", ""),
            r.get("period_end", ""),
        ])

    if not new_rows:
        log.info("append_to_stylists_data_monthly: all rows already present — nothing to write")
        return

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="STYLISTS_DATA_MONTHLY!A2:P",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows},
    ).execute()

    log.info(
        "STYLISTS_DATA_MONTHLY tab: appended %d stylist-month rows (year_months=%s)",
        len(new_rows), year_months,
    )


# ─── CUMULATIVE_MTD tab (weekly snapshots of cumulative month-to-date) ────────
#
# Source-of-truth storage for raw cumulative-MTD snapshots from Elaina's
# weekly POS reports. One row per location per Monday — multiple rows
# accumulate per month as the cumulative grows (Week 1, Week 1+2, Week 1+2+3,
# etc.). The next Monday's pipeline reads the most recent prior snapshot
# and subtracts to produce true weekly values for DATA.
#
# Karissa confirmed 2026-05-26:
#   Q1: cumulative resets at start of each month
#   Q2: Week 1 starts on the 1st (could be a partial Wed-Sun)
#   Q3: last week ends on month's last day (could be a 1-3 day partial)
#   Q4: ALL fields are MTD (everything builds up)
#   Q5: numbers can occasionally DECREASE if refunds happen — accept negatives
#   Q9: salon totals may include corrections that per-stylist totals don't
#       (explains Prior Lake $34 stylist-sum drift — known POS quirk, not bug)
#   Q10: Elaina sends ONE report per Monday, never re-sent
#
# Idempotency key: (loc_name, year_month, week_ending) — three-column natural key.

CUMULATIVE_MTD_HEADERS = [
    "loc_name", "year_month", "week_ending", "platform",
    "guests", "total_sales", "service", "product", "product_pct",
    "ppg", "pph", "avg_ticket", "prod_hours",
    "wax_count", "wax", "wax_pct",
    "color", "color_pct",
    "treat_count", "treat", "treat_pct",
    "source",
]


def _ensure_cumulative_mtd_tab(service, sheet_id: str) -> None:
    """Create CUMULATIVE_MTD with header row if the tab doesn't exist."""
    meta = service.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing_titles = {s["properties"]["title"] for s in meta.get("sheets", [])}
    if "CUMULATIVE_MTD" in existing_titles:
        return

    log.info("CUMULATIVE_MTD tab not found — creating with header row")
    service.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": "CUMULATIVE_MTD"}}}]},
    ).execute()
    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range="CUMULATIVE_MTD!A1:V1",
        valueInputOption="USER_ENTERED",
        body={"values": [CUMULATIVE_MTD_HEADERS]},
    ).execute()


def append_to_cumulative_mtd(
    service,
    config: dict,
    rows: list[dict],
    dry_run: bool = False,
):
    """Append cumulative-MTD snapshot rows. Idempotent on (loc_name, year_month, week_ending).

    Each row supplies the 22 fields named in ``CUMULATIVE_MTD_HEADERS``.
    Reads CUMULATIVE_MTD!A2:C to find existing (loc_name, year_month, week_ending)
    keys; rows whose key is already present are skipped — safe to re-run on
    the same Monday.
    """
    if not rows:
        log.info("append_to_cumulative_mtd: no rows — skipping")
        return

    week_endings = sorted({r.get("week_ending", "") for r in rows if r.get("week_ending")})

    if dry_run:
        log.info(
            "DRY RUN: append_to_cumulative_mtd — would append %d rows for week_endings=%s",
            len(rows), week_endings,
        )
        return

    sheet_id = config["sheet_id"]

    _ensure_cumulative_mtd_tab(service, sheet_id)

    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="CUMULATIVE_MTD!A2:C",
    ).execute()
    existing_keys = {
        (r[0], r[1], r[2]) for r in existing.get("values", []) if len(r) >= 3
    }

    new_rows = []
    for r in rows:
        key = (r.get("loc_name", ""), r.get("year_month", ""), r.get("week_ending", ""))
        if key in existing_keys:
            log.info(
                "append_to_cumulative_mtd: skipping existing (loc=%s, ym=%s, we=%s)",
                *key,
            )
            continue
        new_rows.append([
            r.get("loc_name", ""),
            r.get("year_month", ""),
            r.get("week_ending", ""),
            r.get("platform", ""),
            r.get("guests", 0),
            r.get("total_sales", 0),
            r.get("service", 0),
            r.get("product", 0),
            r.get("product_pct", 0),
            r.get("ppg", 0),
            r.get("pph", 0),
            r.get("avg_ticket", 0),
            r.get("prod_hours", 0),
            r.get("wax_count", 0),
            r.get("wax", 0),
            r.get("wax_pct", 0),
            r.get("color", 0),
            r.get("color_pct", 0),
            r.get("treat_count", 0),
            r.get("treat", 0),
            r.get("treat_pct", 0),
            r.get("source", ""),
        ])

    if not new_rows:
        log.info("append_to_cumulative_mtd: all rows already present — nothing to write")
        return

    # RAW (not USER_ENTERED): the week_ending column is an ISO date string
    # ("2026-05-03"). Under USER_ENTERED, Sheets silently parses it into an
    # Excel serial number (46145), which breaks the next run's idempotency
    # check because the existing-keys reader gets the serial back and the
    # writer-side keys are still strings. RAW keeps the values verbatim.
    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="CUMULATIVE_MTD!A2:V",
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows},
    ).execute()

    log.info(
        "CUMULATIVE_MTD tab: appended %d snapshot rows (week_endings=%s)",
        len(new_rows), week_endings,
    )


# ─── STYLISTS_CUMULATIVE_MTD tab ──────────────────────────────────────────────
#
# Same pattern as CUMULATIVE_MTD but at stylist grain. Idempotency key is
# (year_month, week_ending, name, loc_name).

STYLISTS_CUMULATIVE_MTD_HEADERS = [
    "year_month", "week_ending", "name", "loc_name", "loc_id", "platform",
    "invoices", "guests", "net_service", "net_product",
    "avg_ticket", "pph", "ppg", "production_hours",
    "source",
]


def _ensure_stylists_cumulative_mtd_tab(service, sheet_id: str) -> None:
    """Create STYLISTS_CUMULATIVE_MTD with header row if the tab doesn't exist."""
    meta = service.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing_titles = {s["properties"]["title"] for s in meta.get("sheets", [])}
    if "STYLISTS_CUMULATIVE_MTD" in existing_titles:
        return

    log.info("STYLISTS_CUMULATIVE_MTD tab not found — creating with header row")
    service.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": "STYLISTS_CUMULATIVE_MTD"}}}]},
    ).execute()
    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range="STYLISTS_CUMULATIVE_MTD!A1:O1",
        valueInputOption="USER_ENTERED",
        body={"values": [STYLISTS_CUMULATIVE_MTD_HEADERS]},
    ).execute()


def append_to_stylists_cumulative_mtd(
    service,
    config: dict,
    rows: list[dict],
    dry_run: bool = False,
):
    """Append stylist cumulative-MTD snapshots. Idempotent on (ym, we, name, loc)."""
    if not rows:
        log.info("append_to_stylists_cumulative_mtd: no rows — skipping")
        return

    week_endings = sorted({r.get("week_ending", "") for r in rows if r.get("week_ending")})

    if dry_run:
        log.info(
            "DRY RUN: append_to_stylists_cumulative_mtd — would append %d rows for week_endings=%s",
            len(rows), week_endings,
        )
        return

    sheet_id = config["sheet_id"]

    _ensure_stylists_cumulative_mtd_tab(service, sheet_id)

    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="STYLISTS_CUMULATIVE_MTD!A2:D",
    ).execute()
    existing_keys = {
        (r[0], r[1], r[2], r[3]) for r in existing.get("values", []) if len(r) >= 4
    }

    new_rows = []
    for r in rows:
        key = (
            r.get("year_month", ""),
            r.get("week_ending", ""),
            r.get("name", ""),
            r.get("loc_name", ""),
        )
        if key in existing_keys:
            log.info(
                "append_to_stylists_cumulative_mtd: skipping existing %s",
                key,
            )
            continue
        new_rows.append([
            r.get("year_month", ""),
            r.get("week_ending", ""),
            r.get("name", ""),
            r.get("loc_name", ""),
            r.get("loc_id", ""),
            r.get("platform", ""),
            r.get("invoices", 0),
            r.get("guests", 0),
            r.get("net_service", 0),
            r.get("net_product", 0),
            r.get("avg_ticket", 0),
            r.get("pph", 0),
            r.get("ppg", 0),
            r.get("production_hours", 0),
            r.get("source", ""),
        ])

    if not new_rows:
        log.info("append_to_stylists_cumulative_mtd: all rows already present — nothing to write")
        return

    # RAW: same reason as CUMULATIVE_MTD — the week_ending column is an ISO
    # date that USER_ENTERED would silently convert to a serial number.
    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="STYLISTS_CUMULATIVE_MTD!A2:O",
        valueInputOption="RAW",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows},
    ).execute()

    log.info(
        "STYLISTS_CUMULATIVE_MTD tab: appended %d snapshot rows (week_endings=%s)",
        len(new_rows), week_endings,
    )


# ─── MONTHLY_GOALS tab ────────────────────────────────────────────────────────
#
# Karissa enters per-location monthly $ targets + her two operating-day
# divisors (daily_goal_divisor, day_goal_divisor) by hand each month. The
# YoY report tab needs all three to render her pacing columns. Idempotency
# key is (loc_name, year_month). 6 columns A-F.

MONTHLY_GOALS_HEADERS = [
    "loc_name", "year_month",
    "monthly_goal", "daily_goal_divisor", "day_goal_divisor",
    "source",
]


def _ensure_monthly_goals_tab(service, sheet_id: str) -> None:
    """Create MONTHLY_GOALS with header row if the tab doesn't exist."""
    meta = service.spreadsheets().get(spreadsheetId=sheet_id).execute()
    existing_titles = {s["properties"]["title"] for s in meta.get("sheets", [])}
    if "MONTHLY_GOALS" in existing_titles:
        return

    log.info("MONTHLY_GOALS tab not found — creating with header row")
    service.spreadsheets().batchUpdate(
        spreadsheetId=sheet_id,
        body={"requests": [{"addSheet": {"properties": {"title": "MONTHLY_GOALS"}}}]},
    ).execute()
    service.spreadsheets().values().update(
        spreadsheetId=sheet_id,
        range="MONTHLY_GOALS!A1:F1",
        valueInputOption="USER_ENTERED",
        body={"values": [MONTHLY_GOALS_HEADERS]},
    ).execute()


def append_to_monthly_goals(
    service,
    config: dict,
    rows: list[dict],
    dry_run: bool = False,
):
    """Append per-location monthly goal rows. Idempotent on (loc_name, year_month)."""
    if not rows:
        log.info("append_to_monthly_goals: no rows — skipping")
        return

    year_months = sorted({r.get("year_month", "") for r in rows if r.get("year_month")})

    if dry_run:
        log.info(
            "DRY RUN: append_to_monthly_goals — would append %d rows for year_months=%s",
            len(rows), year_months,
        )
        return

    sheet_id = config["sheet_id"]

    _ensure_monthly_goals_tab(service, sheet_id)

    existing = service.spreadsheets().values().get(
        spreadsheetId=sheet_id,
        range="MONTHLY_GOALS!A2:B",
    ).execute()
    existing_keys = {
        (r[0], r[1]) for r in existing.get("values", []) if len(r) >= 2
    }

    new_rows = []
    for r in rows:
        key = (r.get("loc_name", ""), r.get("year_month", ""))
        if key in existing_keys:
            log.info(
                "append_to_monthly_goals: skipping existing (loc=%s, year_month=%s)",
                key[0], key[1],
            )
            continue
        new_rows.append([
            r.get("loc_name", ""),
            r.get("year_month", ""),
            r.get("monthly_goal", 0),
            r.get("daily_goal_divisor", 0),
            r.get("day_goal_divisor", 0),
            r.get("source", ""),
        ])

    if not new_rows:
        log.info("append_to_monthly_goals: all rows already present — nothing to write")
        return

    service.spreadsheets().values().append(
        spreadsheetId=sheet_id,
        range="MONTHLY_GOALS!A2:F",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": new_rows},
    ).execute()

    log.info(
        "MONTHLY_GOALS tab: appended %d rows (year_months=%s)",
        len(new_rows), year_months,
    )


# ─── Dual-write shadow hook (v2 parallel Sheet) ───────────────────────────────
#
# This is the bridge between the legacy pipeline and the new v2 Sheets. It is
# OFF by default. Flip it on by setting:
#
#     DUAL_WRITE_V2=true        # enable the shadow write
#     V2_MASTER_SHEET_ID=<id>   # v2 master sheet ID
#     V2_COACH_SHEET_ID=<id>    # optional — v2 coach cards sheet ID
#     V2_DRY_RUN=true|false     # override (defaults to the outer dry_run)
#
# The legacy write runs first and is the source of truth. The v2 write runs
# AFTER and is wrapped so any failure (auth, schema mismatch, network) is
# logged but never propagates — production must continue exactly as before.

def _dual_write_v2_enabled() -> bool:
    return os.environ.get("DUAL_WRITE_V2", "").strip().lower() in ("1", "true", "yes", "on")


def _dual_write_v2(
    data: dict,
    coach_cards: dict | None,
    dry_run: bool,
) -> None:
    """
    Shadow-write the enriched pipeline output to the v2 Sheet.
    Never raises — all failures are logged at WARNING.
    """
    if not _dual_write_v2_enabled():
        return

    try:
        master_id = os.environ.get("V2_MASTER_SHEET_ID", "").strip()
        if not master_id:
            log.warning("DUAL_WRITE_V2: V2_MASTER_SHEET_ID not set — skipping shadow write")
            return

        # v2 dry-run defaults to the outer dry_run, but can be overridden.
        v2_dry_env = os.environ.get("V2_DRY_RUN", "").strip().lower()
        if v2_dry_env in ("1", "true", "yes", "on"):
            v2_dry = True
        elif v2_dry_env in ("0", "false", "no", "off"):
            v2_dry = False
        else:
            v2_dry = dry_run

        # Import lazily so this module stays importable without v2 deps on the
        # path (the v2 code imports gspread + our schema module; neither is
        # required for the legacy pipeline).
        from core.google_sheets_store import GoogleSheetsStore
        from core.schema_mapper import (
            map_coach_briefs,
            map_location_rows,
            map_stylist_rows,
        )

        store = GoogleSheetsStore(
            master_sheet_id=master_id,
            coach_cards_sheet_id=os.environ.get("V2_COACH_SHEET_ID") or None,
            dry_run=v2_dry,
        )

        locations = data.get("locations") or []
        stylists = data.get("stylists") or []
        week_ending = data.get("network", {}).get("week_ending", "")

        v2_locations = map_location_rows(locations)
        v2_stylists = map_stylist_rows(stylists, period_end=week_ending)

        caller = "core.sheets_writer.write_all"

        store.write_locations_current(v2_locations, caller=caller)
        store.append_locations_historical(v2_locations, caller=caller)
        store.write_stylists_current(v2_stylists, caller=caller)
        store.append_stylists_historical(v2_stylists, caller=caller)

        if coach_cards:
            briefs = map_coach_briefs(coach_cards)
            if briefs:
                store.write_coach_briefs(
                    briefs,
                    period_end=week_ending,
                    model="",  # model name threaded through in a later phase
                    caller=caller,
                )

        log.info("DUAL_WRITE_V2: shadow write complete (dry_run=%s)", v2_dry)
    except Exception as e:  # noqa: BLE001 — must never propagate
        log.warning(
            "DUAL_WRITE_V2: shadow write failed (non-fatal — legacy write succeeded): %s",
            e,
        )


# ─── Main entry ───────────────────────────────────────────────────────────────

def write_all(
    config: dict,
    data: dict,
    ai_cards: dict,
    coach_cards: dict | None = None,
    dry_run: bool = False,
):
    """Write CURRENT, STYLISTS_CURRENT, ALERTS, coach brief rows, and historical appends in one call."""
    service = _build_service(config) if not dry_run else None
    write_current(service, config, data["locations"], dry_run)
    write_stylists_current(service, config, data["stylists"], dry_run)
    write_alerts(service, config, data["locations"], data["network"], ai_cards, dry_run)

    week_ending = data["network"].get("week_ending", "")

    if coach_cards:
        write_coach_briefs(service, config, coach_cards, week_ending, dry_run)

    append_to_historical(service, config, data["locations"], dry_run)
    append_to_stylists_historical(service, config, data["stylists"], week_ending, dry_run)

    # v2 shadow write — OFF by default, gated by DUAL_WRITE_V2 env var.
    # Runs AFTER legacy writes succeed; any v2 failure is logged, not raised.
    _dual_write_v2(data, coach_cards, dry_run)

    log.info("Sheets write complete (dry_run=%s)", dry_run)
