#!/usr/bin/env python3
"""
build_sheet.py
KPI Platform — Karissa's Salon Network (13 locations)

Sets up a Google Sheet with 4 tabs:
  CURRENT  – Live snapshot of most recent week. Cleared/rewritten every Monday.
  DATA     – Full historical record, append-only.
  GOALS    – Annual targets per location (admin-only, protected label).
  ALERTS   – AI-generated flags from most recent run. Cleared/rewritten every Monday.

Authentication:
  Service account JSON (base64-encoded) in GOOGLE_SERVICE_ACCOUNT_JSON env var.

Config:
  config/customers/karissa_001.json → { "sheet_id": "...", "locations": [...] }

Usage:
  python scripts/build_sheet.py
"""

import os
import sys
import json
import base64
import datetime
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError


# ─── Paths ────────────────────────────────────────────────────────────────────

REPO_ROOT   = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "customers" / "karissa_001.json"

SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]

# ─── Tab names ────────────────────────────────────────────────────────────────

TAB_CURRENT = "CURRENT"
TAB_DATA    = "DATA"
TAB_GOALS   = "GOALS"
TAB_ALERTS  = "ALERTS"
TABS        = [TAB_CURRENT, TAB_DATA, TAB_GOALS, TAB_ALERTS]

# ─── Colors (Google Sheets API uses 0.0–1.0 float components) ─────────────────

def _rgb(r: int, g: int, b: int) -> dict:
    """Convert 0–255 int components to a Sheets API color dict."""
    return {"red": r / 255, "green": g / 255, "blue": b / 255}

C_NAVY       = _rgb(15,  17,  23)   # #0F1117 — header background
C_WHITE      = _rgb(255, 255, 255)  # #FFFFFF — light band / text on dark bg
C_LGRAY      = _rgb(248, 248, 248)  # #F8F8F8 — dark band (alternating rows)
C_RED        = _rgb(255, 0,   0  )  # #FF0000 — GOALS admin warning text
C_HL_RED     = _rgb(255, 229, 229)  # light red    — ALERTS severity HIGH
C_HL_ORANGE  = _rgb(255, 243, 204)  # light amber  — ALERTS severity MEDIUM
C_HL_GREEN   = _rgb(229, 255, 229)  # light green  — ALERTS severity LOW

SEVERITY_COLORS = {
    "HIGH":   C_HL_RED,
    "MEDIUM": C_HL_ORANGE,
    "LOW":    C_HL_GREEN,
}

# ─── Column definitions ───────────────────────────────────────────────────────

# Identical for both CURRENT and DATA tabs.
PERF_HEADERS = [
    "Location Name",    # 0
    "Week Ending",      # 1
    "Platform",         # 2
    "Guest Count",      # 3
    "Total Sales $",    # 4
    "Service $",        # 5
    "Product $",        # 6
    "Product %",        # 7
    "PPG $",            # 8
    "PPH $",            # 9
    "Avg Ticket $",     # 10
    "Prod Hours",       # 11
    "Wax Count",        # 12
    "Wax $",            # 13
    "Wax %",            # 14
    "Color $",          # 15
    "Color %",          # 16
    "Treatment Count",  # 17
    "Treatment $",      # 18
    "Treatment %",      # 19
]

GOALS_HEADERS = [
    "Location Name",
    "Annual Guest Count Goal",
    "Annual Total Sales Goal $",
    "Annual Service Goal $",
    "Annual Product Goal $",
    "Product % Goal",
    "PPG Goal $",
    "PPH Goal $",
    "Avg Ticket Goal $",
    "Color % Goal",
    "Treatment % Goal",
    "Wax % Goal",
]

ALERTS_HEADERS = [
    "Location Name",
    "Alert Type",
    "Severity",
    "Message",
    "Week Ending",
    "Generated By",
]

# ─── Fixed column widths for DATA tab (pixels) ───────────────────────────────
# (CURRENT uses auto-resize instead.)
#
# Spec: Location Name=180, Week Ending=100, Platform=90,
#       dollar columns=90, percent columns=75, count columns=80.

DATA_COL_WIDTHS = [
    180,  # Location Name
    100,  # Week Ending
    90,   # Platform
    80,   # Guest Count       (count)
    90,   # Total Sales $     (dollar)
    90,   # Service $         (dollar)
    90,   # Product $         (dollar)
    75,   # Product %         (percent)
    90,   # PPG $             (dollar)
    90,   # PPH $             (dollar)
    90,   # Avg Ticket $      (dollar)
    80,   # Prod Hours        (count)
    80,   # Wax Count         (count)
    90,   # Wax $             (dollar)
    75,   # Wax %             (percent)
    90,   # Color $           (dollar)
    75,   # Color %           (percent)
    80,   # Treatment Count   (count)
    90,   # Treatment $       (dollar)
    75,   # Treatment %       (percent)
]

GOALS_COL_WIDTHS = [
    180,  # Location Name
    150,  # Annual Guest Count Goal
    160,  # Annual Total Sales Goal $
    150,  # Annual Service Goal $
    150,  # Annual Product Goal $
    110,  # Product % Goal
    100,  # PPG Goal $
    100,  # PPH Goal $
    130,  # Avg Ticket Goal $
    110,  # Color % Goal
    130,  # Treatment % Goal
    110,  # Wax % Goal
]

ALERTS_COL_WIDTHS = [
    180,  # Location Name
    120,  # Alert Type
    90,   # Severity
    420,  # Message  (wide — prose text)
    110,  # Week Ending
    130,  # Generated By
]


# ─── Auth / Config ────────────────────────────────────────────────────────────

def load_config() -> dict:
    if not CONFIG_PATH.exists():
        raise FileNotFoundError(
            f"Config file not found: {CONFIG_PATH}\n"
            "Create config/customers/karissa_001.json with a 'sheet_id' key."
        )
    return json.loads(CONFIG_PATH.read_text())


def build_sheets_service(config: dict):
    raw_b64 = os.environ.get("GOOGLE_SERVICE_ACCOUNT_JSON", "").strip()
    if not raw_b64:
        raise EnvironmentError(
            "GOOGLE_SERVICE_ACCOUNT_JSON environment variable is not set.\n"
            "Export the base64-encoded service account JSON before running."
        )
    try:
        sa_json = base64.b64decode(raw_b64).decode("utf-8")
        sa_info = json.loads(sa_json)
    except Exception as exc:
        raise ValueError(
            f"Could not decode GOOGLE_SERVICE_ACCOUNT_JSON: {exc}"
        ) from exc
    creds = service_account.Credentials.from_service_account_info(
        sa_info, scopes=SCOPES
    )
    return build("sheets", "v4", credentials=creds)


# ─── Spreadsheet helpers ──────────────────────────────────────────────────────

def fetch_spreadsheet(service, spreadsheet_id: str) -> dict:
    return service.spreadsheets().get(spreadsheetId=spreadsheet_id).execute()


def ensure_tabs_exist(service, spreadsheet_id: str, current_ss: dict) -> dict:
    """
    Create any missing tabs in a single batchUpdate call.
    Returns a refreshed spreadsheet dict (makes one extra GET only if needed).
    """
    existing_titles = {s["properties"]["title"] for s in current_ss["sheets"]}
    missing = [t for t in TABS if t not in existing_titles]
    if not missing:
        return current_ss

    add_requests = [
        {"addSheet": {"properties": {"title": title}}} for title in missing
    ]
    service.spreadsheets().batchUpdate(
        spreadsheetId=spreadsheet_id,
        body={"requests": add_requests},
    ).execute()
    print(f"      Created new tab(s): {', '.join(missing)}")
    return fetch_spreadsheet(service, spreadsheet_id)


def extract_sheet_meta(spreadsheet: dict) -> tuple[dict, dict]:
    """
    Returns (sheet_ids, existing_banding) dicts keyed by tab title.
      sheet_ids[title]       → int sheetId
      existing_banding[title] → list of bandedRangeId ints
    """
    sheet_ids       = {}
    existing_banding = {}
    for sheet in spreadsheet["sheets"]:
        title = sheet["properties"]["title"]
        sheet_ids[title] = sheet["properties"]["sheetId"]
        existing_banding[title] = [
            b["bandedRangeId"]
            for b in sheet.get("bandedRanges", [])
        ]
    return sheet_ids, existing_banding


# ─── Low-level request builders ───────────────────────────────────────────────

def _header_cell(text: str) -> dict:
    """Navy background, white bold text."""
    return {
        "userEnteredValue": {"stringValue": text},
        "userEnteredFormat": {
            "backgroundColor": C_NAVY,
            "textFormat": {
                "bold": True,
                "foregroundColor": C_WHITE,
            },
            "verticalAlignment": "MIDDLE",
        },
    }


def _plain_cell(text: str, bg: dict) -> dict:
    return {
        "userEnteredValue": {"stringValue": text} if text else {},
        "userEnteredFormat": {"backgroundColor": bg},
    }


def _empty_cell(bg: dict) -> dict:
    return {
        "userEnteredValue": {},
        "userEnteredFormat": {"backgroundColor": bg},
    }


def _colored_string_cell(text: str, bg: dict) -> dict:
    return {
        "userEnteredValue": {"stringValue": text},
        "userEnteredFormat": {"backgroundColor": bg},
    }


def _req_clear(sheet_id: int) -> dict:
    """Wipe all values and formats on the entire sheet."""
    return {
        "updateCells": {
            "range":  {"sheetId": sheet_id},
            "fields": "userEnteredValue,userEnteredFormat",
        }
    }


def _req_write_rows(sheet_id: int, row_index: int, rows: list) -> dict:
    return {
        "updateCells": {
            "start":  {"sheetId": sheet_id, "rowIndex": row_index, "columnIndex": 0},
            "rows":   rows,
            "fields": "userEnteredValue,userEnteredFormat",
        }
    }


def _req_freeze(sheet_id: int, rows: int = 1, cols: int = 0) -> dict:
    grid_props = {"frozenRowCount": rows}
    fields     = "gridProperties.frozenRowCount"
    if cols:
        grid_props["frozenColumnCount"] = cols
        fields += ",gridProperties.frozenColumnCount"
    return {
        "updateSheetProperties": {
            "properties": {
                "sheetId":      sheet_id,
                "gridProperties": grid_props,
            },
            "fields": fields,
        }
    }


def _req_banding(sheet_id: int, num_cols: int) -> dict:
    """
    Add alternating row banding starting at row index 1 (below the header).
    firstBandColor  → white  (rows 2, 4, 6 …)
    secondBandColor → #F8F8F8 (rows 3, 5, 7 …)
    endRowIndex omitted intentionally — covers the entire sheet.
    """
    return {
        "addBanding": {
            "bandedRange": {
                "range": {
                    "sheetId":        sheet_id,
                    "startRowIndex":  1,
                    "startColumnIndex": 0,
                    "endColumnIndex": num_cols,
                    # endRowIndex omitted → extends to end of sheet
                },
                "rowProperties": {
                    "firstBandColor":  C_WHITE,
                    "secondBandColor": C_LGRAY,
                },
            }
        }
    }


def _req_delete_banding(banding_id: int) -> dict:
    return {"deleteBanding": {"bandedRangeId": banding_id}}


def _req_col_widths(sheet_id: int, widths: list) -> list:
    return [
        {
            "updateDimensionProperties": {
                "range": {
                    "sheetId":    sheet_id,
                    "dimension":  "COLUMNS",
                    "startIndex": i,
                    "endIndex":   i + 1,
                },
                "properties": {"pixelSize": w},
                "fields":     "pixelSize",
            }
        }
        for i, w in enumerate(widths)
    ]


def _req_auto_resize(sheet_id: int, num_cols: int) -> dict:
    return {
        "autoResizeDimensions": {
            "dimensions": {
                "sheetId":    sheet_id,
                "dimension":  "COLUMNS",
                "startIndex": 0,
                "endIndex":   num_cols,
            }
        }
    }


def _req_basic_filter(sheet_id: int, num_cols: int) -> dict:
    return {
        "setBasicFilter": {
            "filter": {
                "range": {
                    "sheetId":        sheet_id,
                    "startRowIndex":  0,
                    "startColumnIndex": 0,
                    "endColumnIndex": num_cols,
                }
            }
        }
    }


# ─── Tab request builders ─────────────────────────────────────────────────────

def build_current_requests(sheet_id: int, stale_banding: list) -> list:
    """
    CURRENT tab — live weekly snapshot.
    Navy header, freeze row 1 + col A, alternating bands, auto-resize.
    """
    reqs = []
    reqs += [_req_delete_banding(bid) for bid in stale_banding]
    reqs.append(_req_clear(sheet_id))
    reqs.append(_req_write_rows(
        sheet_id, 0,
        [{"values": [_header_cell(h) for h in PERF_HEADERS]}],
    ))
    reqs.append(_req_freeze(sheet_id, rows=1, cols=1))
    reqs.append(_req_banding(sheet_id, len(PERF_HEADERS)))
    reqs.append(_req_auto_resize(sheet_id, len(PERF_HEADERS)))
    return reqs


def build_data_requests(sheet_id: int, stale_banding: list) -> list:
    """
    DATA tab — full historical record, append-only.
    Same header as CURRENT. Fixed column widths (no auto-resize).
    Filter on all columns.
    """
    reqs = []
    reqs += [_req_delete_banding(bid) for bid in stale_banding]
    reqs.append(_req_clear(sheet_id))
    reqs.append(_req_write_rows(
        sheet_id, 0,
        [{"values": [_header_cell(h) for h in PERF_HEADERS]}],
    ))
    reqs.append(_req_freeze(sheet_id, rows=1, cols=1))
    reqs.append(_req_banding(sheet_id, len(PERF_HEADERS)))
    reqs.append(_req_basic_filter(sheet_id, len(PERF_HEADERS)))
    reqs += _req_col_widths(sheet_id, DATA_COL_WIDTHS)
    return reqs


def build_goals_requests(
    sheet_id: int,
    stale_banding: list,
    location_names: list,
) -> list:
    """
    GOALS tab — annual targets per location.
    Row 1 header uses navy bg but col A1 text is red bold ("Admin Only").
    13 pre-populated location rows with blank goal cells.
    """
    reqs = []
    reqs += [_req_delete_banding(bid) for bid in stale_banding]
    reqs.append(_req_clear(sheet_id))

    # Build header row — all cells start navy/white ...
    header_row = {"values": [_header_cell(h) for h in GOALS_HEADERS]}

    # ... then we'll override A1 afterwards with red text.
    # Build the 13 location data rows with alternating backgrounds.
    data_rows = []
    for i, name in enumerate(location_names[:13]):
        bg = C_WHITE if i % 2 == 0 else C_LGRAY
        cells = [_plain_cell(name, bg)] + [
            _empty_cell(bg) for _ in range(len(GOALS_HEADERS) - 1)
        ]
        data_rows.append({"values": cells})

    reqs.append(_req_write_rows(sheet_id, 0, [header_row] + data_rows))

    # Override A1: navy bg, red bold text — admin warning.
    reqs.append({
        "updateCells": {
            "start": {"sheetId": sheet_id, "rowIndex": 0, "columnIndex": 0},
            "rows": [{
                "values": [{
                    "userEnteredValue": {
                        "stringValue": "GOALS — Admin Only. Do not edit."
                    },
                    "userEnteredFormat": {
                        "backgroundColor": C_NAVY,
                        "textFormat": {
                            "bold":            True,
                            "foregroundColor": C_RED,
                        },
                    },
                }]
            }],
            "fields": "userEnteredValue,userEnteredFormat",
        }
    })

    reqs.append(_req_freeze(sheet_id, rows=1))
    reqs += _req_col_widths(sheet_id, GOALS_COL_WIDTHS)
    return reqs


def build_alerts_requests(
    sheet_id: int,
    stale_banding: list,
    location_names: list,
    today: str,
) -> list:
    """
    ALERTS tab — AI-generated flags.
    3 sample rows pre-populated (one per severity level).
    Severity drives row background color: HIGH=red, MEDIUM=amber, LOW=green.
    """
    loc = location_names  # shorthand

    # Sample rows: [Location Name, Alert Type, Severity, Message, Week Ending, Generated By]
    sample_data = [
        [
            loc[0] if len(loc) > 0 else "Location 1",
            "RECOGNITION",
            "LOW",
            "Strong week — highest PPH in the network at $XX/hr",
            today,
            "KPI AI",
        ],
        [
            loc[1] if len(loc) > 1 else "Location 2",
            "WATCH",
            "MEDIUM",
            "Product % dropped 4 points vs last week. Coach attention recommended.",
            today,
            "KPI AI",
        ],
        [
            loc[2] if len(loc) > 2 else "Location 3",
            "GOAL_PACE",
            "HIGH",
            "Tracking 18% below annual sales goal pace. Needs recovery plan.",
            today,
            "KPI AI",
        ],
    ]

    rows = [{"values": [_header_cell(h) for h in ALERTS_HEADERS]}]
    for row_data in sample_data:
        bg    = SEVERITY_COLORS[row_data[2]]
        cells = [_colored_string_cell(str(v), bg) for v in row_data]
        rows.append({"values": cells})

    reqs = []
    reqs.append(_req_clear(sheet_id))
    reqs.append(_req_write_rows(sheet_id, 0, rows))
    reqs.append(_req_freeze(sheet_id, rows=1))
    reqs += _req_col_widths(sheet_id, ALERTS_COL_WIDTHS)
    return reqs


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("╔══════════════════════════════════════════════════╗")
    print("║  KPI Sheet Builder — Karissa's Salon Network     ║")
    print("╚══════════════════════════════════════════════════╝")

    # ── 1. Load config
    print("\n[1/5] Loading config ...")
    config = load_config()

    spreadsheet_id = config.get("sheet_id", "").strip()
    if not spreadsheet_id or spreadsheet_id == "REPLACE_WITH_YOUR_GOOGLE_SHEET_ID":
        print(
            "\n❌  sheet_id is not set in config/customers/karissa_001.json.\n"
            "    Replace the placeholder value with your real Google Sheet ID.",
            file=sys.stderr,
        )
        sys.exit(1)

    raw_locations = config.get("locations", [])
    # Support both flat string list (legacy) and object list {id, name, platform}
    if raw_locations and isinstance(raw_locations[0], dict):
        location_names = [loc["name"] for loc in raw_locations]
    else:
        location_names = list(raw_locations)
    while len(location_names) < 13:
        location_names.append(f"Location {len(location_names) + 1}")
    location_names = location_names[:13]

    print(f"      Sheet ID  : {spreadsheet_id}")
    print(f"      Locations : {', '.join(location_names)}")

    # ── 2. Authenticate
    print("\n[2/5] Authenticating with Google Sheets API ...")
    service = build_sheets_service(config)
    print("      ✓ Authenticated")

    # ── 3. Ensure all 4 tabs exist
    print("\n[3/5] Ensuring all 4 tabs exist ...")
    spreadsheet = fetch_spreadsheet(service, spreadsheet_id)
    spreadsheet = ensure_tabs_exist(service, spreadsheet_id, spreadsheet)

    sheet_ids, existing_banding = extract_sheet_meta(spreadsheet)
    for tab in TABS:
        bcount = len(existing_banding.get(tab, []))
        note   = f"({bcount} existing banding range(s) will be replaced)" if bcount else ""
        print(f"      {tab:<10} sheetId={sheet_ids[tab]}  {note}")

    # ── 4. Build all requests
    today = datetime.date.today().strftime("%Y-%m-%d")
    print(f"\n[4/5] Building formatting requests (today = {today}) ...")

    all_requests = (
        build_current_requests(
            sheet_ids[TAB_CURRENT],
            existing_banding.get(TAB_CURRENT, []),
        )
        + build_data_requests(
            sheet_ids[TAB_DATA],
            existing_banding.get(TAB_DATA, []),
        )
        + build_goals_requests(
            sheet_ids[TAB_GOALS],
            existing_banding.get(TAB_GOALS, []),
            location_names,
        )
        + build_alerts_requests(
            sheet_ids[TAB_ALERTS],
            existing_banding.get(TAB_ALERTS, []),
            location_names,
            today,
        )
    )
    print(f"      {len(all_requests)} total API requests queued")

    # ── 5. Execute
    print("\n[5/5] Executing batchUpdate ...")
    service.spreadsheets().batchUpdate(
        spreadsheetId=spreadsheet_id,
        body={"requests": all_requests},
    ).execute()

    print(
        "\n✅  Sheet setup complete!\n"
        f"   https://docs.google.com/spreadsheets/d/{spreadsheet_id}\n"
    )


if __name__ == "__main__":
    try:
        main()
    except FileNotFoundError as exc:
        print(f"\n❌  Config error: {exc}", file=sys.stderr)
        sys.exit(1)
    except EnvironmentError as exc:
        print(f"\n❌  Auth error: {exc}", file=sys.stderr)
        sys.exit(1)
    except ValueError as exc:
        print(f"\n❌  Value error: {exc}", file=sys.stderr)
        sys.exit(1)
    except HttpError as exc:
        print(f"\n❌  Google API error: {exc}", file=sys.stderr)
        sys.exit(1)
